server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  server:
    port: 8081
  info:
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

eureka:
  instance:
    metadata-map:
      actual-port: ${management.server.port}
  client:
    eureka-server-u-r-l-context: ${DISCOVERY_URL:localhost}

logging:
  file:
    path: ./log