server:
  port: 8080
  shutdown: graceful
  forward-headers-strategy: framework

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    process:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_URL:http://localhost/eureka}

logging:
  file:
    path: ./log