spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${eureka_servers:http://localhost:8761/eureka}

server:
  port: 8000

management:
  server:
    port: 8001
  info:
    os:
      enabled: true
    java:
      enabled: true
    process:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
    circuitbreakers:
      enabled: true

logging:
  file:
    path: build/log
