spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - StripPrefix=1
      routes:
        - id: app-service
          uri: http://app-service:8080
          predicates:
            - Path=/app/**